#!/usr/bin/env bash

set -euo pipefail

# Update sapporo_config/slurm.env with Slurm connection info and job settings.
#
# Usage: bash scripts/update_slurm_env.sh
#
# Requires .env in the project root (run `cp env.<env> .env` first).
# Reads Slurm parameters from .env, resolves dynamic values (IP, JWT, UID),
# and writes sapporo_config/slurm.env.
#
# Idempotent: safe to run multiple times (e.g., to renew JWT).
# The generated slurm.env is mounted into the sapporo container and sourced
# by sapporo_config/run.slurm.sh at job submission time, so changes take
# effect immediately without restarting the sapporo container.

ROOT_DIR="$(cd "$(dirname "$0")" && cd .. && pwd)"
OUTPUT_FILE="${ROOT_DIR}/sapporo_config/slurm.env"

# --- Load .env (required) ---

ENV_FILE="${ROOT_DIR}/.env"
if [[ ! -f "${ENV_FILE}" ]]; then
  echo "ERROR: .env not found at ${ENV_FILE}" >&2
  echo "  Run 'cp env.<env> .env' first." >&2
  exit 1
fi
set -a
# shellcheck source=/dev/null
source "${ENV_FILE}"
set +a

# --- Resolve dynamic values ---

# Master node IP from hostname
SLURM_MASTER_NODE_IP=$(getent hosts "${SLURM_MASTER_NODE_HOSTNAME}" | awk '{print $1}')
if [[ -z "${SLURM_MASTER_NODE_IP}" ]]; then
  echo "ERROR: Failed to resolve hostname '${SLURM_MASTER_NODE_HOSTNAME}'" >&2
  exit 1
fi
echo "Resolved ${SLURM_MASTER_NODE_HOSTNAME} -> ${SLURM_MASTER_NODE_IP}"

# JWT token
SLURM_JWT=$(scontrol token lifespan="${SLURM_TOKEN_LIFESPAN}" | grep -oP 'SLURM_JWT=\K.*')
if [[ -z "${SLURM_JWT}" ]]; then
  echo "ERROR: Failed to generate Slurm JWT token" >&2
  exit 1
fi
echo "Generated JWT token (lifespan=${SLURM_TOKEN_LIFESPAN}s)"

# User ID
SLURM_UID="${UID}"
echo "UID=${SLURM_UID}"

# --- Write slurm.env ---

cat > "${OUTPUT_FILE}" <<EOF
# Generated by scripts/update_slurm_env.sh at $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Do not edit manually. Run 'bash scripts/update_slurm_env.sh' to regenerate.
SLURM_UID=${SLURM_UID}
SLURM_MASTER_NODE_IP=${SLURM_MASTER_NODE_IP}
SLURM_MASTER_NODE_PORT=${SLURM_MASTER_NODE_PORT}
SLURM_JWT=${SLURM_JWT}
SLURM_PARTITION=${SLURM_PARTITION}
SLURM_CPUS_PER_TASK=${SLURM_CPUS_PER_TASK}
SLURM_MEMORY_PER_CPU=${SLURM_MEMORY_PER_CPU}
EOF

echo "Written: ${OUTPUT_FILE}"
